/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import BackGround from "./BackGround"
import GameControler from "./GameControler"
import Bird from "./Bird"
import Pipe from "./Pipe"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=480;
    static height:number=852;
    static scaleMode:string="noscale";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="GameStage.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("BackGround.ts",BackGround);
        reg("GameControler.ts",GameControler);
        reg("Bird.ts",Bird);
        reg("Pipe.ts",Pipe);
    }
}
GameConfig.init();